### ISSUE TITLE
Parameter optional value not handled correctly. 

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-developer#151]
On https://developer.wordpress.org/reference/hooks/customize_partial_render_partial-id/ the parameters are stripping the prefix 'Optional' from a parameter, without showing the Optional header.

<img width="602" alt="Screen Shot 2022-11-03 at 10 47 23 am" src="https://user-images.githubusercontent.com/767313/199628421-825a3f39-3bb4-4b5a-a9e3-3b47e69de20f.png">

https://core.trac.wordpress.org/browser/tags/6.1/src/wp-includes/customize/class-wp-customize-partial.php#L248
<img width="828" alt="Screen Shot 2022-11-03 at 10 48 20 am" src="https://user-images.githubusercontent.com/767313/199628517-9a252650-1e59-47c0-ac43-00d90c088f0e.png">

It seems like perhaps we shouldn't be stripping just `Optional` from the prefix, but only when it's `Optional.`.

**Comment by pkevan** [comment]
Curiosity got the better of me, and I traced this back to when it was introduced: https://meta.trac.wordpress.org/changeset/1019 - seems like we could either search for the use cases mentioned `Many times (likely older docs) it is followed by a comma,` or just switch to removing the case where it is [handled](https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer/inc/template-tags.php#L816-L819).

**Comment by coffee2code** [comment]
At the time of implementation, core was much less consistent with the `Optional.` syntax (per WordPress Inline Documentation standards [for @param](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#1-functions-class-methods)) than it is now.

However, even now there are existing usage of `Optional,` (using a comma). While they could be fixed in core (and should), there is a high potential of a future core code change making this minor oversight. Since it's fairly trivial to account for this,  `get_params()`, as noted above, was [changed to accommodate this](https://meta.trac.wordpress.org/changeset/1019), but that implementation is indeed now a bit overzealous.

Fix incoming.
