### ISSUE TITLE
Functions should have a section about their hooks

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-developer#21]
### Discussed in https://github.com/WordPress/wporg-developer/discussions/13

<div type='discussions-op-text'>

<sup>Originally posted by **dd32** May 23, 2022</sup>
The only way to see a list of filters/actions present within a function is to expand the code block and read through.

There should be a dedicated list of filters (and their short description) present on the function page, linking to the hooks info page.</div>

Ian also notes:

> It'd be really helpful if that section also listed the earliest hook at which you can call the function (when applicable). Also any other pre-conditions.

**Comment by StevenDufresne** [comment]
**Huddle Chat Notes:**
- We have the data for hooks (since we have a "hooks" section in the docs).
- Getting the order is a bit more challenging.

**Comment by dd32** [comment]
> The only way to see a list of filters/actions present within a function is to expand the code block and read through.

It turns out this is wrong. the page DOES display the hooks, just not in a super obvious way. They're included in the "Related" section, the highlighted items here are a filter and action:

<img width="874" alt="Screen Shot 2022-05-30 at 4 56 17 pm" src="https://user-images.githubusercontent.com/767313/170934773-2c670bb6-7f37-4e6f-8948-be6f474b10b8.png">

That section is a bit noisy, we don't need to know that the function uses `__()` or `do_action` surely (See: all the X'd items).. but I never realised hooks were listed in there, as it's not exactly clear at all.

**Comment by iandunn** [comment]
>  I never realised hooks were listed in there, as it's not exactly clear at all

Doh, me neither. 

> That section is a bit noisy, we don't need to know that the function uses __() or do_action surely (See: all the X'd items)

💯

**Comment by dd32** [comment]
It might be worth closing this, and opening a new issue for the remaining part of the issue:

> It'd be really helpful if that section also listed the earliest hook at which you can call the function (when applicable). Also any other pre-conditions.

**Comment by iandunn** [comment]
Opened #115 for the remaining task
