### ISSUE TITLE
Searchbox Autocomplete missing.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#321]
The autocomplete for searches when using the code reference is not working. It was working when we did a first pass of this design. Was it removed purposefully? That is a very well used feature.

## Screenshots
<img width="367" alt="Screenshot 2023-11-02 at 3 55 10 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/dd9bb87c-5195-4229-9b57-d36f846306d3">

should be:
<img width="594" alt="Screenshot 2023-11-02 at 3 54 28 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/399f4abc-d1d9-4d76-9471-674b58862098">

**Comment by StevenDufresne** [comment]
This was also working on the homepage as well.

**Comment by adamwoodnz** [comment]
It has not been removed intentionally.

**Comment by outdoor2kode** [comment]
There was originally a search bar on the homepage, right? I remember there used to be one.

However, in the current production version of the code, I’ve noticed that [this condition](https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/inc/template-tags.php#L1768) would never evaluates to true on the homepage, resulting in the search bar not being displayed there. Adding `is_front_page()` would bring it back.

And I initially thought that the search functionality wouldn't work on the current production either, but it turns out that you need to type at least three letters before suggestions pop up.

**Comment by adamwoodnz** [comment]
> There was originally a search bar on the homepage, right? I remember there used to be one.

Not the [home page](https://developer.wordpress.org/), it's on the [reference landing page](https://developer.wordpress.org/reference/).

The search has been removed from the new home page, see https://github.com/WordPress/wporg-developer/issues/309#issuecomment-1787512401

The requirement for this issue is to get it working again on https://developer.wordpress.org/redesign-test/reference/ and the code reference search at https://developer.wordpress.org/redesign-test/?s=block
