### ISSUE TITLE
"New and Updated in" page on Mobile is confusing.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#329]
Looking at this page: https://developer.wordpress.org/redesign-test/reference/since/6.1.0/.

This page looks pretty confusing on mobile. The button styles vary and the layout isn't predictable. The [current version](https://developer.wordpress.org/reference/since/6.1.0/) doesn't have the ability the filter by version type. 
 

## Screenshot (500px)
<img width="400" alt="Screenshot 2023-11-03 at 2 57 40 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/7721d042-91d6-47a5-9832-6e9e44f9e95c">

**Comment by adamwoodnz** [comment]
@WordPress/meta-design your input please 🙂

**Comment by jasmussen** [comment]
Good issue. These things can be really hard to pin down in the static mockups.

I would love @fcoveram input on this one, as it affects the filter bar, but as a provocation, can we do this?

![Screenshot 2023-11-06 at 09 30 38](https://github.com/WordPress/wporg-developer/assets/1204802/f40a30ef-dbc2-444e-b6f5-514e37985acc)

That is:

* Just remove the version filtering for now, we can add it if there are requests for it and revisit at that point
* Remove the "Apply", so you like today, can only filter by one type at a time. The filter buttons become links rather than toggles.

A "provocation" in this case isn't meant to offend anyone, it's rather to ask questions that may have obvious answers but are worth resurfacing just to make sure we're not missing something very basic.

For what it's worth, I also think it could work by simply removing the version dropdown entirely, and then only showing the "Apply" button after you've chosen a filter button that isn't "all".

**Comment by fcoveram** [comment]
I thought the filter behavior we wanted was like radio, but looking at [the link](https://developer.wordpress.org/redesign-test/reference/since/6.1.0/.) shared by Steve, the filter can be multiple.

If that is the case, plus adding the release number filter, we should change to something like this.

![Design of code reference page with filters applied](https://github.com/WordPress/wporg-developer/assets/895819/7a1fbad2-93be-4684-b1d5-ff1d2cb9333e)

The default page is filtered by the last release number, whereas the search results page (not included in the mockups above) has the "Code reference" filter in the bar.

Am I understanding this correctly?

**Comment by adamwoodnz** [comment]
> I thought the filter behavior we wanted was like radio

I see now that the current production page has a single filter experience. These staging filters are shared between the search page and this 'since' page, and I think somewhere along the way the functionality has become the same between the two, which I guess is good for users. But the difference in filtering you've noted might be confusing.

The query filter implementation seems nice. Might be a big too much for MVP, maybe next iteration?

**Comment by StevenDufresne** [comment]
I don't think jumping between versions on this page is a completely necessary feature, especially since it's new. I would vote to hide it for launch.

**Comment by fcoveram** [comment]
I don't fully follow your suggestion @StevenDufresne, you mean hiding the filter and dropdown selector and keep only the list?

**Comment by StevenDufresne** [comment]
The control that allow us to "filter" by the version is a new control and we haven't proven that users need to flip between versions to see the changes. It isn't completely necessary for this view and since on mobile the layout right now is pretty distracting, we can probably hide it on mobile until users request that we turn it on. I don't like hiding things on mobile views because the layout doesn't work, but I feel it's a fair compromise for right now.


<img width="300" alt="Screenshot 2023-11-09 at 10 41 25 AM" src="https://github.com/WordPress/wporg-developer/assets/1657336/2d37385b-080f-454b-88d9-cbf7974440e7">

**Comment by fcoveram** [comment]
I see. I also don't like hiding things on mobile. So in that case, I would hide it completely.
