### ISSUE TITLE
Reduce the number of handbook edit entry points.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#339]
We currently give users 3 visible entry points to edit a handbook article. I'm not sure that should be promoted so heavily. It adds visual cruft and  I think the last "edit this article" link is good enough.

@ndiego

<img src="https://github.com/WordPress/wporg-developer/assets/1657336/67158c02-e1f9-484e-8e8a-caeaa843684e" width="300">

<img src="https://github.com/WordPress/wporg-developer/assets/1657336/56274e0c-2995-42bd-b641-4db6bd514383" width="300">

<img src="https://github.com/WordPress/wporg-developer/assets/1657336/166ed6bb-5fdd-4475-9550-b59edbd7d9a0" width="300">

**Comment by ndiego** [comment]
Yes, at the very least, the link in the sidebar should be removed. There is a dedicated issue for that here: https://github.com/WordPress/wporg-developer/issues/296

And yes, I think we could do away with the Edit link in the header now that there will be an "Improve it on GitHub" link. Not that this link does not work in the Staging site, which is already reported here: https://github.com/WordPress/wporg-developer/issues/328

@adamwoodnz this is unrelated to this issue, but note that the "Last updated" date for articles in the Block Editor Handbook are not correct since the entire handbook resyncs periodically throughout the day. If it's possible to remove the  "Last updated" date for the Block Editor Handbook, that would be great.

**Comment by adamwoodnz** [comment]
Fixed by #346
