### ISSUE TITLE
Avoid orphaned brackets for hooks (and probably signature)

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#380]
We should avoid wrapping only the ")" character for hooks. Since this is the same code as the signature at the top of the page, it may also happen there but I don't have an example of that.

## Screenshot
<img width="712" alt="Screenshot 2023-11-17 at 12 24 09 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/5d4190b0-a66b-4153-9c27-ab19c6e67758">

**Comment by StevenDufresne** [comment]
Good example:
https://developer.wordpress.org/redesign-test/reference/functions/wp_insert_term/

**Comment by StevenDufresne** [comment]
It appears to be an existing problem. However, looking into this, it isn't apparent why we need to display all the arguments in this context:
- The are pretty overwhelming
- They are links so if a user wants to see the arguments they can click the links.

With that in mind, I suggest we consider truncated the arguments for this view only:

| Current | Redesign | Option |
|--------| --------|--------|
| <img width="942" alt="Screenshot 2023-11-20 at 4 23 16 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/21284030-8b48-46ca-990f-c52b2e502805"> | <img width="734" alt="Screenshot 2023-11-20 at 4 19 49 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/7657d26e-9dbd-4fa4-bd3f-bcd9be963d68"> | <img width="744" alt="Screenshot 2023-11-20 at 4 19 38 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/89c59942-bc15-48ce-9916-3718948729b8"> | 


@ndiego @WordPress/meta-design

**Comment by jasmussen** [comment]
Fascinating question. The trailing parenthesis, WordPress/Nacin-spaced, works essentially like a widow but for code. Definitely agree that doesn't look good. 

But instead of truncating — although I'm less of a dev these days, I personally appreciate the fuller example — can we handle this the same as we handle widows in a paragraph of text? That is, always ensure there's not just one word wrapping onto a new line. So instead of:

```
do_action( "create_{$taxonomy}", int $term_id, int $tt_id, array $args 
)
```

we do this:

```
do_action( "create_{$taxonomy}", int $term_id, int $tt_id, array 
$args )
```

Probably not trivial, but in some cases we have replaced a space ` ` with a non breaking space `&nbsp;` between the last two words to ensure they count as one.

**Comment by ndiego** [comment]
This does not solve the root issue, but I was noticing that the width of the content on pages without a chapters list is fairly narrow which exacerbates this. 

On the current site, the width is 960px, and it's 680px on the new site. I know this was specified in the design, but I am wondering if we should bump this back up to 960px. That would make the content feel less cramped.

**Comment by jasmussen** [comment]
Just to test it out, here's 680:

![Screenshot 2023-11-21 at 10 17 48](https://github.com/WordPress/wporg-developer/assets/1204802/2b9677c2-eab1-4cae-b133-dc631cd7c573)

Here's a hacky 960 that doesn't do it justice:

![Screenshot 2023-11-21 at 10 18 40](https://github.com/WordPress/wporg-developer/assets/1204802/2b4b9c87-1f1f-4a03-bdac-f083dfbc203e)

Ignoring the hackiness and the TOC floating incorrectly, I'm not sure the latter actually benefits this, or legibility. It would also create a difference between pages that have chapters (3 column layout) vs. pages that don't.

We _could_ potentially introduce a wider max-width, 960 seems too much IMO, but maybe 800 or so, and apply it on dev sections. But this would make it depart from News, which is 680, so we'd want to be intentional about this. I'm not sure it's a win overall, but it's an option that can be considered.

**Comment by fcoveram** [comment]
Agree with Joen, 960px risks displaying long lines of text and making it hard to read. If the current spacing system has a value between 800 and 850, I would apply it only in Developers, as other sections like News, don't present these kinds of layouts.

**Comment by StevenDufresne** [comment]
I've opened a PR using `&nbsp;`, [suggested by joen](https://github.com/WordPress/wporg-developer/issues/380#issuecomment-1818476818), to just stop the breakage. I don't think there was any support for truncating the arguments so I'll leave that as an unused solution here.

If we want to update the content width, it probably should be done in a different ticket. The discussion would be hard to find here.
