### ISSUE TITLE
Plugin handbook landing page is not at the top of the chapter list

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-developer#391]
Pages appear to be listed alphabetically, we want them to be ordered as they are on the current site.

![Screenshot 2023-11-21 at 3 25 41 PM](https://github.com/WordPress/wporg-developer/assets/1017872/f352d572-dca6-4740-a159-7d2c971857e5)

**Comment by adamwoodnz** [comment]
Looks to be the same for `/rest-api/`

**Comment by outdoor2kode** [comment]
Left some findings first.

Have the same issue:
`/rest-api/`
`/themes/`
`/plugins/`

The difference in results compared to other standard handbooks is likely due to the manifest_url used to fetch the handbook data.

For example: 
`rest-api`: https://raw.githubusercontent.com/WP-API/docs/master/bin/manifest.json
`advanced-administration`: https://raw.githubusercontent.com/WordPress/Advanced-administration-handbook/main/bin/handbook-manifest.json

In `advanced-administration`'s file, items are not sorted by alphabet, but in `rest-api`, they are.
This would affect the orders in their post lists and further lead to an incorrect chapter list.
`rest-api`: `wp-admin/edit.php?post_type=rest-api-handbook`
`advanced-administration`: `wp-admin/edit.php?post_type=adv-admin-handbook`

That said, the orders of the post lists are the same on the prod, but the chapter list shows the order correctly. I guess there must be some logic being changed by accident or just not working correctly.

Will look into this further moving forward.

**Comment by outdoor2kode** [comment]
I tried to modify the `manifest.json` but realized it's maintained by different stakeholders. It's not that changes can't be made, but rather, they might require a request to them. For instance, I guess Gutenberg might be maintaining its own Handbook, so the Block Editor handbook sends back a JSON where the order is automatically correct, but other handbooks just don't.

However, it was mentioned above that even in production, the JSON order is not right as well. The difference lies in the fact that in production, `dynamic_sidebar( get_query_var( 'current_handbook' ) );` is used to get the chapter list. This function retrieves sidebar information from the dashboard under `Appearance -> Widgets`. The sidebar information, in turn, is defined in `Appearance -> Menus`. Put simply, it fetches the list from the Menu, and users can adjust this order themselves.

Here, the chapter-list block, for some reason, does not use this method to fetch the chapter list. Instead, it directly uses the post list (via `wp_list_pages()`) from the handbook CPT, which means the order can't be adjusted in the Menu.

**However, I discovered that it's possible to adjust the `Page Attributes` meta for each post in the post editor. Since `'sort_column' => 'menu_order, post_title'` is set, this seems to be the simplest and most convenient way to make the list order identical to that in production.**

P.S. Originally, I wanted to at least get the "handbook front page" post to the top of the list by adding some sort of logic in the code, but I couldn't find a method to identify which post is the "handbook front page." This label is neither a taxonomy nor a post meta. Just curious if anyone has any insights about this label and knows how to get a post through based on it?

**Comment by outdoor2kode** [comment]
Alright, I used [REST API Handbook](https://developer.wordpress.org/redesign-test/rest-api/) as an example and successfully changed the Chapter List to match the production by adjusting the `order`. We can make the same adjustments to the posts in production, and then the List Order will be correct.

![image](https://github.com/WordPress/wporg-developer/assets/18050944/f39fe882-d33d-48c9-8aec-545dd6ca67e9)

| Production | Redesign |
|-|-|
| ![image](https://github.com/WordPress/wporg-developer/assets/18050944/98e26c52-f5d4-42db-9f1d-d9532f890847) | ![image](https://github.com/WordPress/wporg-developer/assets/18050944/1e16fc6c-0123-467a-a9ec-4261e9cb27de) |

**Comment by outdoor2kode** [comment]
Done reordering all the handbooks' chapter lists that have this issue after launching ✅
