### ISSUE TITLE
Improve table design

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#492]
I just noticed that the table design feels a bit unfinished. Here is an example on the [FAQ](https://developer.wordpress.org/block-editor/getting-started/faq/#are-there-keyboard-shortcuts-for-gutenberg) page.  Based on the [Figma design](https://developer.wordpress.org/block-editor/getting-started/faq/#are-there-keyboard-shortcuts-for-gutenberg), I don't think the white lines are supposed to be there.

<img width="1950" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/4ebd9d63-e81b-4379-9b49-c7d83e99a3d2">

cc @marko-srb @fcoveram

**Comment by ryelle** [comment]
You're right, it should be like this:

<img width="703" alt="Screenshot 2024-02-02 at 11 54 55 AM" src="https://github.com/WordPress/wporg-developer/assets/541093/42c114ad-4d91-4587-9c91-b4d17429dfbd">

It's a technical problem— the issue is that the handbook content is not _actually_ using gutenberg, it's just [faking the right classes](https://github.com/WordPress/wporg-developer/blob/f44d12894f1c8b7b5b2988c05f259bddfe9e857c/source/wp-content/themes/wporg-developer-2023/functions.php#L640), but core only loads the table CSS if the block is on the page.

(this is also why https://github.com/WordPress/wporg-developer/issues/414 will be harder than "just turn it on.")

**Comment by ryelle** [comment]
@ndiego Do you still want design feedback here, or should this just be marked to fix?

**Comment by ndiego** [comment]
> @ndiego Do you still want design feedback here, or should this just be marked to fix?

Yeah, I think we can just move ahead with a fix. Thanks for the context!

**Comment by ndiego** [comment]
> this is also why https://github.com/WordPress/wporg-developer/issues/414 will be harder than "just turn it on."

Yeah, I wish there was a way to automatically convert the markdown into blocks behind the scenes. That would make everything a lot easier.
