### ISSUE TITLE
3 column layout broken with Firefox ESR

### ISSUE THREAD

**Issue by ronnyadsetts** [WordPress/wporg-developer#508]
See this page as an example of the breakage - it applies to all of the documentation pages at https://developer.wordpress.org as far as I can see:

https://developer.wordpress.org/advanced-administration/security/mfa/

I use my web browser at about 1300 pixels wide. The breakpoints for this issue seem to be about 1384 at the top and 752 on the bottom end. Anywhere within that width, the site doesn't work for me. I'm using Firefox ESR 115.9.1.

Two screenshots attached, one at the top of the page showing the whitespace where the <main> content should be; the second showing scrolled down with the <div class="wp-block-wporg-sidebar-container"> with "position: fixed" overlaying the <main>.

![screenshot-developer wordpress org-2024 04 11-09_23_50](https://github.com/WordPress/wporg-developer/assets/1334007/86888718-c34c-47e5-8c5a-95ebbdf50ab5)

![screenshot-developer wordpress org-2024 04 11-09_25_18](https://github.com/WordPress/wporg-developer/assets/1334007/d16c4542-dbf2-4523-956f-805bd85bb67f)

I noticed this a while ago but didn't know where to report issues. It's finally got sufficiently annoying that I took the time to find this github repo.

Let me know if you need more info to reproduce.

**Comment by adamwoodnz** [comment]
Thanks for the report. I can reproduce with Firefox ESR on MacOS, but not any other browser so far.

**Comment by ryelle** [comment]
This is the same issue as https://github.com/WordPress/wporg-parent-2021/issues/167 — the problem is that this layout uses `:has()`, which was not available in Firefox until 121. WordPress.org roughly follows the core browser support list, and this version of Firefox is not supported.

That said, it looks like [the current ESR release](https://whattrainisitnow.com/release/?version=esr) is 128, which should include support for this CSS selector.

**Comment by ronnyadsetts** [comment]
See https://github.com/WordPress/wporg-parent-2021/issues/167#issuecomment-2542496516 for a FF option to enable the feature to allow this to work.
