### ISSUE TITLE
Mobile :- Page Scrollbar is not proper way to address their is a other elements also.

### ISSUE THREAD

**Issue by NidhiDhandhukiya** [WordPress/wporg-developer#544]
Check on this Page :- https://developer.wordpress.org/advanced-administration/security/mfa/
Check on mobile screen.

You can able to see a scrollbar when we scroll over there.
It is not a proper way because user who may not aware about that scrollbar they don't able to check other things there in the breadcrumbs.

![Image](https://github.com/user-attachments/assets/aacb2567-0efc-4f2b-b969-24598c03c6f7)

**Comment by ryelle** [comment]
This is intentional, as part of the design of this section for small screens. When the breadcrumbs overflow, they have that gradient overlay which should clue users that there's something there. We're using this pattern in a few places across the site. Also, depending on your browser & OS settings, you could see a scroll bar.

![Image](https://github.com/user-attachments/assets/19cf887b-f4ef-419f-8cf4-5ab93ae55991)

See https://github.com/WordPress/wporg-mu-plugins/issues/535, which includes this decision in the linked figma files.
