### ISSUE TITLE
Source code preview for Classes is too narrow

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-developer#76]
The source-code displayed for classes is too narrow, caused by the table of contents.

It might make more sense to display the Method list before the Source code too, as that's likely more important to the reader.

<img width="895" alt="Screen Shot 2022-06-03 at 5 00 00 pm" src="https://user-images.githubusercontent.com/767313/171803938-969c1e4b-f349-4094-8092-35322f8f2538.png">

**Comment by adamwoodnz** [comment]
Some options:
- float the contents top right when the browser is wide enough, otherwise hide it visually, leaving it still accessible by screen readers
- move the contents alongside the class title (may work better if the search button moves into the header
- include it in a sidebar on the left

**Comment by tellyworth** [comment]
I'd also add the possibility:

* Remove the TOC entirely

**Comment by iandunn** [comment]
Here's how some other docs handle it:

* https://jestjs.io/docs/mock-function-api - collapses
* https://reactjs.org/docs/hooks-reference.html#gatsby-focus-wrapper - always shows
* https://nodejs.org/dist/latest-v18.x/docs/api/http.html - always shows
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter - moves into sidebar

I think the MDN design is an interesting idea. I don't like the idea of hiding it since it feels useful to me, and even more useful when I'm on a smaller device and scrolling is worse (have to use gesture, page is longer, no pageup/down).
